<?xml version="1.0"?>
<robot name="sensors_diffbot" xmlns:xacro="http://ros.org/wiki/xacro">
  
  <xacro:property name="package_name" value="mobile_robots_control"/>
  <xacro:property name="PI" value="3.14159265"/>
  
  <xacro:property name="wheelSeparation" value="0.13"/>
  <xacro:property name="wheelDiameter" value="0.07"/>
  <xacro:property name="wheelThickness" value="0.024"/>
  <xacro:property name="base_elevation" value="0.01"/>
  
  <xacro:include filename="$(find ${package_name})/urdf/sensors_diffbot_gz.xacro"/>
  
  
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_elevation}" rpy="0 0 0"/>
  </joint>

  <link name="base_link"> <!-- Important: Every visual, collision and inertial tag has its own origin -->
    <visual>
      <origin xyz="-0.033 0.0 0.04" rpy="0 0 ${PI}"/>
      <geometry>
        <mesh filename="package://${package_name}/meshes/base_plate.stl" scale="1 1 1"/>
      </geometry>
      <material name="Blue"> <!-- Color in Rviz2 (inside visual tag) -->
        <color rgba="${0/255} ${0/255} ${255/255} 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="-0.033 0 0.04" rpy="0 0 0"/>
      <geometry>
        <box size="0.2 0.1 0.01"/>
      </geometry>
    </collision>
    <!-- Collision tag added to stabilize the robot -->
    <collision> 
      <origin xyz="0.06 0 0.002" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.01" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${wheelDiameter-base_elevation}" rpy="0 0 0"/>
      <mass value="10"/>
      <inertia ixx="0.333333" ixy="0.0" ixz="0.0"  iyy="0.333333" iyz="0.0"  izz="0.6" />
    </inertial>
  </link>


  <!-- Wheels definition (joints and links) -->
  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0 ${wheelSeparation/2} ${wheelDiameter/2-base_elevation}" rpy="${-PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0.015" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://${package_name}/meshes/wheel_ring.stl" scale="1 1 1"/>
      </geometry>
      <material name="white"/> <!-- Color in Rviz2 (inside visual tag) -->
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheelThickness}" radius="${wheelDiameter/2}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="5" />
      <inertia ixx="0.0135417" ixy="0.0" ixz="0.0"  iyy="0.0135417" iyz="0.0"  izz="0.025" />
      </inertial>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0 ${-wheelSeparation/2} ${wheelDiameter/2-base_elevation}" rpy="${-PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 -0.015" rpy="${PI} 0 0"/> <!-- -z and r=PI for the other wheel -->
      <geometry>
        <mesh filename="package://${package_name}/meshes/wheel_ring.stl" scale="1 1 1"/>
      </geometry>
      <material name="white"/> <!-- Color in Rviz2 (inside visual tag) -->
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheelThickness}" radius="${wheelDiameter/2}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="5" />
      <inertia ixx="0.0135417" ixy="0.0" ixz="0.0"  iyy="0.0135417" iyz="0.0"  izz="0.025" />
    </inertial>
  </link>

  <!-- Caster wheel definition (joints and links) -->
  <joint name="caster_base_joint" type="continuous">
    <origin xyz="-0.104 0 0.015" rpy="0 0 ${PI}" />
    <parent link="base_link" />
    <child link="caster_base_link" />
    <axis xyz="0 0 1" />
  </joint>
  
  <link name="caster_base_link">
    <visual>
      <origin xyz="0 0 0.015" rpy="${-PI} 0 0" />
      <geometry>
        <mesh filename="package://${package_name}/meshes/base_caster.stl" />
      </geometry>
    </visual>
    <inertial> <!-- inertia tag must be set for this link -->
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0.5" />
      <inertia ixx="0.00004" ixy="0" ixz="0" iyy="0.00004" iyz="0" izz="0.00001" />
    </inertial>
  </link>

  <joint name="caster_wheel_joint" type="continuous">
    <origin xyz="0.015014 -0.00012272 -0.01" rpy="0 ${-PI/2} ${PI/2}" />
    <parent link="caster_base_link" />
    <child link="caster_wheel_link" />
    <axis xyz="0 0 1" />
  </joint>
  
  <link name="caster_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://${package_name}/meshes/caster_wheel.stl" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder length="0.01" radius="0.015" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="6.93889390390723E-18 -2.62037475051713E-11 -2.77710070911708E-09" rpy="0 0 0" />
      <mass value="0.08" />
      <inertia ixx="0.0004" ixy="0" ixz="0" iyy="0.0004" iyz="0" izz="0.00001" />
    </inertial>
  </link>
  
  
  <!-- ************************ SENSORS FRAME DEFINITION ************************ -->
  <!-- IMU -->
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>
  <link name="imu_link"/>
  
  <!-- LIDAR -->
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="-0.04 0 0.07" rpy="0 0 0"/>
  </joint>
  <link name="lidar_link">
    <visual>
      <origin xyz="-0.0275 -0.0275 -0.02" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://${package_name}/meshes/Lidar_pacecat.stl" scale="0.001 0.001 0.001" />
      </geometry>
    </visual>
  </link>
  
  
  <!-- CAMERA -->
  <joint name="camera_joint" type="fixed">
    <origin xyz="0.04 0 0.06" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera_frame"/>
  </joint>
  <link name="camera_frame">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.07 0.03"/>
      </geometry>
    </visual>
    <!-- Since the camera is a sensor, collision and inertial tags are optional -->
  </link>
  
  
  <!-- SONAR -->
  <joint name="sonar_joint" type="fixed">
    <origin xyz="0.04 0 0.01" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="sonar_link"/>
  </joint>
  <link name="sonar_link">
    <visual>
      <origin xyz="0 0.025 0" rpy="${PI/2} 0 ${-PI/2}"/>
      <geometry>
        <mesh filename="package://${package_name}/meshes/Sonar_hcsr04.stl" scale="0.001 0.001 0.001" />
      </geometry>
    </visual>
  </link>


</robot>

