controller_manager:
  ros__parameters:
    update_rate: 100 #Hz
    
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      # Note: the joint velocity is instantaneously reached
      
    #joint_state_broadcaster:
     # type: joint_state_broadcaster/JointStateBroadcaster
     #THIS IS NOT REQUIRED BECAUSE GAZEBO PUGIN PUBLISHES JOINT STATES, BUT VELOCITY AND EFFORT ARE NOT PUBLISHED
 
velocity_controller:
  ros__parameters:
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      #- effort
    joints:
      - leftfront_joint
      - rightfront_joint
      - rightback_joint
      - leftback_joint


